name: $(SourceBranchName)_$(Rev:r)
pr: none

variables:
  - group: build-secrets

pool:
  vmImage: 'windows-latest'

steps:
- task: Gradle@2
  displayName: Build & Test Application
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    tasks: 'assembleDebug test coveralls'
    options: '-PCOVERALLS_REPO_TOKEN=$env:COVERALLS_REPO_TOKEN -PCI_NAME=$env:CI_NAME'
  env:
    CI_NAME: $(CI_NAME)
    COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
- task: PublishPipelineArtifact@1
  displayName: Save APK
  inputs:
    artifactName: 'apk'
    targetPath: 'app/build/outputs/apk/debug'
- task: PublishPipelineArtifact@1
  displayName: Save Unit Test Reports
  inputs:
    artifactName: 'reports'
    targetPath: 'app/build/reports'
